### ISSUE TITLE
[Chatie/docs] Page build failure

### ISSUE THREAD

**Issue by lijiarui** [Chatie/docs#25]
The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

So, gitbook cannot sync with github.

**Comment by huan** [comment]
![image](https://user-images.githubusercontent.com/1361891/56852142-c9c26480-6949-11e9-9036-fcfe6ed61e49.png)

According to the above error information, please check <https://github.com/Chatie/docs/blob/master/root/examples.md> at line 5.

**Comment by lijiarui** [comment]
thanks.

**Comment by lijiarui** [comment]
This is because GitHub pages are not compatible with some special style on gitbook....

**Comment by lijiarui** [comment]
done
