### ISSUE TITLE
Why don't we have book.json

### ISSUE THREAD

**Issue by lijiarui** [Chatie/docs#4]
see https://toolchain.gitbook.com/config.html

All Configuration is set in book.json, especially the default language setting, but this repo miss book.json or it has set someplace else?

**Comment by zixia** [comment]
We use .gitbook.yml instead.

**Comment by lijiarui** [comment]
I'm looking in the doc of version3.2.3, which is higher than 3.0.0 as the following shows:

Image from https://toolchain.gitbook.com/
![image](https://user-images.githubusercontent.com/6419514/47625629-3f977000-db61-11e8-9429-4f0f3b37fc58.png)

And, this doc says all configuration is set in book.json():

Image from https://toolchain.gitbook.com/config.html
![image](https://user-images.githubusercontent.com/6419514/47625668-7d949400-db61-11e8-884e-96ba14dbc56e.png)

So I'm wondering whether we are using different doc....
