### ISSUE TITLE
Cannot use templates to Importing file from another git

### ISSUE THREAD

**Issue by lijiarui** [Chatie/docs#5]
Using template: https://github.com/Chatie/docs/blob/master/root/wechaty/api.md  as gitbook docs says(https://toolchain.gitbook.com/templating/conrefs.html) But it cannot work as expect online.

Actually, when I run localhost, I find it can import other files in API, it works well.

![image](https://user-images.githubusercontent.com/6419514/47616637-a6ce0980-dafa-11e8-85a1-39637170eae3.png)

While when I commit to GitHub, the online version cannot import API successfully:

![image](https://user-images.githubusercontent.com/6419514/47616660-e85eb480-dafa-11e8-8c49-6a4e056a2952.png)

This is because it failed to exec pre-push hook script:
```shell
➜  root git:(master) git push origin master

> @chatie/docs@0.0.29 lint /Users/jiaruili/git/docs
> npm run lint:md && npm run lint:yaml


> @chatie/docs@0.0.29 lint:md /Users/jiaruili/git/docs
> markdownlint *.md docs/*.md docs/**/*.md


> @chatie/docs@0.0.29 lint:yaml /Users/jiaruili/git/docs
> yamllint .gitbook.yml

✔ YAML Lint successful.
v0.0.30
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 688 bytes | 688.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To https://github.com/Chatie/docs
   def8079..4eb27aa  master -> master
  ____ _ _        ____            _
 / ___(_) |_     |  _ \ _   _ ___| |__
| |  _| | __|    | |_) | | | / __| '_ \
| |_| | | |_     |  __/| |_| \__ \ | | |
 \____|_|\__|    |_|    \__,_|___/_| |_|

 ____                              _ _
/ ___| _   _  ___ ___ ___  ___  __| | |
\___ \| | | |/ __/ __/ _ \/ _ \/ _` | |
 ___) | |_| | (_| (_|  __/  __/ (_| |_|
|____/ \__,_|\___\___\___|\___|\__,_(_)




 ### Npm verion bumped and pushed by inner push inside hook pre-push ###
 ------- vvvvvvv outer push will be canceled, never mind vvvvvvv -------



Failed to exec pre-push hook script
error: failed to push some refs to 'https://github.com/Chatie/docs'
```

**Comment by lijiarui** [comment]
This is not because the pre-push, but the page build failed, it's better to see in the `Setting` page but I don 't have the authority.

> The page build failed for the `master` branch with the following error:
>
> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by lijiarui** [comment]
strange.... In f1adf84cf88f118db8a82dfe181600ffcf4f6a67 commit,  I remove  import files and put all api docs in the file, the page build also failed, but I can see api result in the online version:

![image](https://user-images.githubusercontent.com/6419514/47629690-9dcf4d80-db77-11e8-87b0-4cded207e20d.png)

**Comment by zixia** [comment]
Closing the issues without any explanations feels more like spamming.
